# Generated by Django 6.0 on 2026-01-02 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
                ('Catogery', models.CharField(max_length=50)),
                ('mfg_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
