# Generated by Django 6.0 on 2026-01-05 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macanda', '0004_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='product',
            new_name='product_id',
        ),
    ]
