# Generated by Django 6.0 on 2026-01-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macanda', '0005_rename_product_offer_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousalimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousal/')),
            ],
        ),
        migrations.CreateModel(
            name='footerimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='footer/')),
            ],
        ),
        migrations.CreateModel(
            name='headerimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='header/')),
            ],
        ),
    ]
