# Generated by Django 6.0 on 2026-01-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macanda', '0007_fileupload_delete_carousalimage_delete_footerimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
