# Generated by Django 6.0 on 2026-01-14 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macanda', '0008_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
