# Generated by Django 6.0 on 2026-01-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macanda', '0014_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousalimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousal/')),
            ],
        ),
    ]
