# Generated by Django 6.0.1 on 2026-01-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macanda', '0021_remove_deliveryboy_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoyOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
