# Generated by Django 6.0.1 on 2026-01-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macanda', '0022_deliveryboyotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='address',
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='vehicle_no',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
