# Generated by Django 6.0.1 on 2026-01-28 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macanda', '0023_remove_deliveryboy_address_deliveryboy_vehicle_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryBoy',
        ),
        migrations.DeleteModel(
            name='DeliveryBoyOTP',
        ),
    ]
