# Generated by Django 6.0.1 on 2026-01-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macanda', '0024_delete_deliveryboy_delete_deliveryboyotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('vehicle_no', models.CharField(max_length=50)),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
    ]
