# Generated by Django 6.0 on 2026-01-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macanda', '0002_rename_catogery_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdt_image',
            field=models.ImageField(default=None, upload_to='products/'),
            preserve_default=False,
        ),
    ]
