# Generated by Django 6.0 on 2026-01-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macanda', '0006_carousalimage_footerimage_headerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.DeleteModel(
            name='carousalimage',
        ),
        migrations.DeleteModel(
            name='footerimage',
        ),
        migrations.DeleteModel(
            name='headerimage',
        ),
    ]
