# Generated by Django 6.0 on 2026-01-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macanda', '0009_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
