# Generated by Django 6.0 on 2026-01-15 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macanda', '0011_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
