# Generated by Django 6.0.1 on 2026-01-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macanda', '0020_deliveryboy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deliveryboy',
            name='vehicle_no',
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
